# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Runs tests with coverage"
    lane :testCoverage do
      gradle(task: "jacocoTestDebugUnitTestReport")
    end

  desc "Capture screenshots"
    lane :screenshot do
        build_android_app(
          task: 'assemble',
          build_type: 'Debug'
        )
        build_android_app(
          task: 'assemble',
          build_type: 'AndroidTest'
        )
        capture_android_screenshots(
            tests_apk_path: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk",
            app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
            skip_open_summary: false,
        )
    end

  desc "Deploy a new version to Internal Testers"
  lane :deployInternal do
    increment_version_name(
        gradle_file: "app/build.gradle"
        bump_type: 'patch'
    )
    increment_version_code(
        gradle_file_path: "app/build.gradle"
    )

    changelog_from_git_commits(
      between: ["7dc9034", "HEAD"],
      pretty: "- (%ae) %s",
    )

    gradle(
        task: "bundle",
        build_type: "release",
        print_command: false,
        properties: {
            "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
            "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
            "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
            "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
        }
    )
    upload_to_play_store(
        json_key: ENV["ANDROID_JSON_KEY_FILE"],
        track: "internal",
    )
  end
end
