name: Test and Deploy Coverage

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Run tests with coverage
        run: bundle exec fastlane android testCoverage

      - name: Deploy coverage to pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /home/runner/work/FitnessJournal/FitnessJournal/coverage-report/data/jacocoHtml
          token: ${{ secrets.PAGES_DEPLOY_KEY }}